export class Peticion {
    constructor(
        public id?: number,
        public apoyo_economico?: boolean,
        public atencion_parto?: boolean,
        public derivacion_canalizacion?: boolean,
        public cita_coloquio?: boolean,
        public consejo_orientacion?: boolean,
        public servicios_legales?: boolean,
        public fianzas_conmutas?: boolean,
        public formacion_capacitacion?: boolean,
        public guarderia_kinder?: boolean,
        public hospitalizacion_medica?: boolean,
        public informacion?: boolean,
        public integracion_comunitaria?: boolean,
        public internamiento?: boolean,
        public organizacion_planeacion?: boolean,
        public internamiento_forzado?: boolean,
        public recuperacion_escolar?: boolean,
        public sevicio_social?: boolean,
        public terapia?: boolean,
        public visita_familiar?: boolean,
        public examenes_cuidados_med?: boolean,
        public alimentacion?: boolean,
        public servicio_higiene?: boolean,
        public ocupacion_trabajo?: boolean,
        public medicamentos?: boolean,
        public burocratico?: boolean,
        public otro?: boolean,
        public parcero_id?: number
    ) { }
}